# Generated by Django 5.2.7 on 2025-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0013_review_reviewimage_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='check_in',
            field=models.DateField(blank=True, help_text='Standard check-in date.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='check_out',
            field=models.DateField(blank=True, help_text='Standard check-out date.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rules_and_etiquette',
            field=models.JSONField(blank=True, help_text="List of rules in JSON format, e.g., ['No smoking', 'No pets allowed']", null=True),
        ),
    ]
