# Generated by Django 5.2.7 on 2025-11-22 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0016_alter_property_check_in_alter_property_check_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('inquiries', models.PositiveIntegerField(default=0)),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='villas.property')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('property', 'date')},
            },
        ),
    ]
