# Generated by Django 5.2.7 on 2025-11-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0017_dailyanalytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyanalytics',
            name='inquiries',
        ),
    ]
