# Generated by Django 5.2.7 on 2025-11-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0018_remove_dailyanalytics_inquiries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='google_calendar_id',
        ),
    ]
