# Generated by Django 5.2.7 on 2025-11-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
    ]
