# Generated by Django 5.2.7 on 2025-11-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('branding', 'Branding'), ('templates', 'Templates'), ('legal_forms', 'Legal Forms'), ('training', 'Training'), ('market_research', 'Market Research'), ('external_tools', 'External Tools')], max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='resources/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
