# Generated by Django 5.2.7 on 2025-11-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VilaListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('property_name', models.CharField(max_length=255)),
                ('property_photo', models.ImageField(upload_to='vila_listings/')),
                ('property_document', models.FileField(blank=True, null=True, upload_to='vila_listings/docs/')),
                ('property_brief', models.TextField()),
            ],
        ),
    ]
